name: flask CICD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Packages
        run: pip install flask
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{secret.DOCKERHUB_USERNAME}}
          password: ${{secret.DOCKERHUB_TOKEN}}
      - name: Build and release to Dockerhub
        env:
          NAME: kyla333
          REPO: flaskweb
        run: |
          docker build -t $REPO .
          docker tag $REPO:latest $NAME/$REPO:latest
          docker push $NAME/$REPO:latest